### PR TITLE
Support GHA

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Review by dataflake — DISMISSED** [review]
Would you reconsider moving configuration out of setup.cfg? I don't see why this is necessary.

**Comment by icemac** [comment]
@dataflake wrote:
> Would you reconsider moving configuration out of setup.cfg? I don't see why this is necessary.

It makes meta/config easier as the `setup.cfg` is the same for all projects. In https://github.com/zopefoundation/meta/pull/35 I added support for buildout recipes which need additional flake8 configuration. Maybe we could move it back to `setup.cfg` in a later step (when we have to parametrize `setup.cfg`) but now it would require more work. Additionally all configuration needed for the tests is currently in one place: `tox.ini`.

**Comment by dataflake** [comment]
> It makes meta/config easier as the `setup.cfg` is the same for all projects. In [zopefoundation/meta#35](https://github.com/zopefoundation/meta/pull/35) I added support for buildout recipes which need additional flake8 configuration. Maybe we could move it back to `setup.cfg` in a later step (when we have to parametrize `setup.cfg`) but now it would require more work. Additionally all configuration needed for the tests is currently in one place: `tox.ini`.

I understand what you mean, but if I step back from the specific issue and look at the larger picture what I am seeing is that you are changing sensible configurations just to make the work of this generic configuration generator easier. That's the wrong direction. I am happy to get ideas and inspiration from the sample configurations, but this is not a one-size-fits-all situation. Please do not make plans to run that over all packages.

**Comment by icemac** [comment]
@dataflake As you value having the flake8 config in `setup.cfg` and I want to run `meta/config` on as much as possible packages of zopefoundation (to reduce the manual work) I am going to invest the time to move the flake8 config back to where it originated from.

**Comment by dataflake** [comment]
It's not just the flake8 config. The same is true for coverage config that's still in those hidden `.coveragerc` files in many repositories. Same issue - configuration spread over several files, sometimes even hidden files, that could be centralized in a single obvious place, which is setup.cfg.

**Comment by icemac** [comment]
@dataflake I am with you, I also want the configuration in a single central place. It thought we decided that this central place is `tox.ini`. The `config/meta` script already has the coverage config there. And it also had the flake8 config until https://github.com/zopefoundation/meta/pull/42/commits/bcb6eca09d4fbd3fe4e10cb89942adecee9fee58 (which is not yet merged to master). I do not care which file this central place is. But we should decide for one.

**Comment by icemac** [comment]
I am closing this PR in favor of #8. Which supersedes this one.

**Pull request closed without merging**
