### PR TITLE
Make zLOG work both with python2 and python3 via six

### PR DESCRIPTION
**Pull request by mexicarne**
Make this package py3 compatible.

### CODE REVIEW

**Comment by tseaver** [comment]
I'd kind of prefer to do this without adding the 'six' dependency (likely just by lifting the 'reraise' code from it).  But I wouldn't block a merge of this PR as it stands.

**Comment by mexicarne** [comment]
Here is version of the patch that doesn't imply six, but it fails to bytecode compile with python3 - the execution flow switching to python2's "raise E,V,T" for some reason. And with six it just works.
https://people.freebsd.org/~rm/zLOG-not-working-with-p3.diff
Many zope/plone ports require six as dependency, so it should'n be a problem.

**Comment by tseaver** [comment]
I meant to do something more like:

https://github.com/repoze/repoze.tm2/blob/master/repoze/tm/__init__.py#L9-L30

**Comment by mexicarne** [comment]
Yes, this like an option too.

**Comment by tseaver** [comment]
Ugh, needs test coverage first.

**Comment by tomgross** [comment]
A Python 3 compatible version without six is here: https://github.com/zopefoundation/zLOG/pull/2

**Comment by tomgross** [comment]
#2 was merged

**Comment by mexicarne** [comment]
Great! Any plans to make a PyPi release?

**Pull request closed without merging**
